project2: AdjacencyList.cpp AdjacencyMatrix.cpp Graph.cpp HexMap.cpp AdjacencyList.h AdjacencyMatrix.h Graph.h HexMap.h project2.cpp
	g++ -Wall -pedantic -g -std=c++11  AdjacencyList.cpp AdjacencyMatrix.cpp Graph.cpp HexMap.cpp project2.cpp

clean:
	rm -f project2 project2.exe 
