project3: AdjacencyMatrix.cpp Graph.cpp HexMap.cpp AdjacencyMatrix.h Graph.h HexMap.h project3.cpp distance_between_hexes.cpp
	g++ -g -std=c++11  AdjacencyMatrix.cpp Graph.cpp HexMap.cpp project3.cpp distance_between_hexes.cpp

clean:
	rm -f project3 
